image: python:3.10

stages:
  - lint
  - build
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - pip install pytest pytest-cov flake8 rasa

lint:
  stage: lint
  script:
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=venv/

train-model:
  stage: build
  script:
    - rasa train
  artifacts:
    paths:
      - models/
    expire_in: 1 week

unit-test:
  stage: test
  script:
    - pytest tests/ --cov=. --cov-report=xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

test-nlu:
  stage: test
  script:
    - rasa test nlu --nlu data/nlu.yml --cross-validation
  needs:
    - train-model
  allow_failure: true

test-core:
  stage: test
  script:
    - rasa test core --stories tests/test_stories.yml
  needs:
    - train-model
  allow_failure: true

e2e-test:
  stage: test
  script:
    - rasa test --stories tests/test_stories_e2e.yml #--e2e
    # For custom Python tests, start servers in background
    # These need to be run/deployed locally with valid API's
    #- rasa run --enable-api --port 5005 &
    #- sleep 5  # Give server time to start
    #- rasa run actions &
    #- sleep 10  # Give actions server time to start
    # Run tests
    #- pytest tests/test_e2e.py -v
    # Clean up servers
    #- pkill -f "rasa run"
  needs:
    - train-model
  allow_failure: true

pages:
  stage: deploy
  script:
    - mkdir -p public/coverage
    - pytest tests/ --cov=. --cov-report=html:public/coverage
    - rasa data validate --domain domain.yml
  artifacts:
    paths:
      - public
  only:
    - main

  # This job will run on pushes to the 'main' branch
sync_to_github:
  stage: deploy
  image: alpine/git:latest # A lightweight image with git pre-installed
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"' # Only run this job for the 'main' branch
  script:
    - echo "Setting up Git user..."
    - git config --global user.name "GitLab CI" # Set a generic user name for commits
    - git config --global user.email "mailblog967+github@gmail.com"
    
    # Fetch the repository first
    - git fetch origin
    - git checkout -B main origin/main
    
    - echo "Adding GitHub remote..."
    # The GH_PAT variable is automatically available here
    # Use oauth2:${GH_PAT} for authentication
    - git remote add github https://oauth2:${GH_PAT}@github.com/yorkyabroad/rasa-chat-ex.git
    
    - echo "Pushing to GitHub..."
    # Push the current branch to GitHub
    - git push github main
    - git push --tags github
  variables:
    # Ensure this variable name matches the 'Key' you set in GitLab CI/CD settings
    # The actual value is loaded securely from GitLab's CI/CD variables.
    GH_PAT: $GH_PAT