name: Code Quality and Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly scan for vulnerabilities

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install bandit pylint safety
          
      - name: Run Bandit security scan
        run: bandit -r . -x .git,__pycache__,.pytest_cache,venv,env,tests,htmlcov -s B603 -ll || true
        
      - name: Run Pylint
        run: pylint --disable=C0111,C0103 actions/ || true
        
      - name: Check for vulnerabilities
        run: safety check -r requirements.txt || true
        
      - name: Run tests with coverage
        run: pytest --cov=actions tests/
        
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml