name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Install rasa for GitHub Actions environment (Python 3.10 is compatible)
        pip install rasa>=3.6.0
        
    - name: Debug environment
      run: |
        pip list
        ls -la
        ls -la tests/
        
    - name: Run unit tests
      run: |
        python -m pytest tests/ -k "not test_e2e" -v
        
    - name: Start Rasa server for E2E tests
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: |
        # Train a model first
        rasa train
        # Start Rasa server in background
        rasa run --enable-api --port 5005 &
        # Start Actions server in background
        rasa run actions --debug &
        # Give servers time to start
        sleep 30
        # Check if servers are running
        curl http://localhost:5005/ || echo "Rasa server not responding"
        
    - name: Run E2E tests
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: |
        python -m pytest tests/test_e2e.py -v
        
    - name: Run tests with coverage
      run: |
        python -m pytest tests/ --cov=actions --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: yorkyabroad/rasa-chat-ex       
        file: ./coverage.xml
        fail_ci_if_error: false